/**
 * TypeScript version of the Python MetaDataExtractor class
 *
 * This module loads pre-extracted metadata from a JSON file
 * that was generated by the extract_metadata.py script
 */

import { readable, writable, derived, type Readable } from 'svelte/store';
import { browser } from '$app/environment';
import type { SequenceData } from '../types/sequence';

// Define types for our metadata
interface MetadataItem {
	sequence: SequenceData;
	tags?: string[];
	is_favorite?: boolean;
}

// Define the type for a sequence with thumbnail
export interface SequenceWithThumbnail {
	id: string;
	name: string;
	thumbnailUrl: string;
	sequenceData: SequenceData;
	isFavorite: boolean;
	tags: string[];
}

/**
 * Internal store for metadata state management
 */
interface MetadataState {
	data: Record<string, MetadataItem>;
	isLoading: boolean;
	isLoaded: boolean;
	error: string | null;
}

// Create internal store for metadata state
const metadataStore = writable<MetadataState>({
	data: {},
	isLoading: false,
	isLoaded: false,
	error: null
});

// Derived store for sequences with thumbnails
export const sequencesStore: Readable<SequenceWithThumbnail[]> = derived(
	metadataStore,
	($state) => {
		if (!$state.isLoaded || $state.isLoading) {
			return [];
		}

		return convertRawMetadataToSequences($state.data);
	}
);

// Track loading promise to prevent duplicate loads
let loadingPromise: Promise<Record<string, MetadataItem>> | null = null;

/**
 * Convert raw metadata directly to SequenceWithThumbnail objects
 * @param metadataData The raw metadata data object
 * @returns Array of sequence objects with thumbnails
 */
export function convertRawMetadataToSequences(
	metadataData: Record<string, MetadataItem>
): SequenceWithThumbnail[] {
	return Object.entries(metadataData)
		.map(([thumbnailPath, metadata]) => {
			try {
				// Extract the filename from the path
				const pathParts = thumbnailPath.split('/');
				const filename = pathParts[pathParts.length - 1];
				const id = filename.replace('.png', '').toLowerCase();

				// Get the sequence name from the metadata
				const name =
					Array.isArray(metadata.sequence) &&
					metadata.sequence.length > 0 &&
					metadata.sequence[0]?.word
						? metadata.sequence[0].word
						: `Unnamed (${id})`;

				return {
					id,
					name,
					thumbnailUrl: thumbnailPath,
					sequenceData: metadata.sequence,
					isFavorite: metadata.is_favorite || false,
					tags: metadata.tags || []
				};
			} catch (error) {
				console.error(`Error processing sequence data for ${thumbnailPath}:`, error);
				return null;
			}
		})
		.filter(Boolean) as SequenceWithThumbnail[];
}

/**
 * Safe fetch that only runs in browser context
 * @param url The URL to fetch
 * @returns Promise with the response
 */
async function safeFetch(url: string): Promise<Response> {
	// Check if we're in browser context
	if (!browser) {
		throw new Error('Cannot fetch in server context');
	}

	// Use a base URL for relative paths to ensure they work correctly
	const baseURL = window.location.origin;
	const fullURL = url.startsWith('http') ? url : new URL(url, baseURL).toString();

	// Create an abort controller with timeout
	const controller = new AbortController();
	const timeoutId = setTimeout(() => controller.abort(), 5000);

	try {
		const response = await fetch(fullURL, {
			cache: 'no-cache',
			headers: {
				Accept: 'application/json'
			},
			signal: controller.signal
		});
		return response;
	} catch (error) {
		if (error instanceof Error && error.name === 'AbortError') {
			throw new Error(`Fetch request to ${url} timed out after 5 seconds`);
		}
		throw error;
	} finally {
		clearTimeout(timeoutId);
	}
}

/**
 * Load metadata from JSON file
 */
async function loadMetadata(): Promise<Record<string, MetadataItem>> {
	// If already loading, return the existing promise
	if (loadingPromise) {
		return loadingPromise;
	}

	// Update loading state
	metadataStore.update((state) => ({
		...state,
		isLoading: true,
		error: null
	}));

	// Create and store the loading promise
	loadingPromise = (async () => {
		// Check if we're in a browser environment
		if (!browser) {
			console.warn('Metadata loading skipped: Not in browser context');

			// Mark as loaded but empty to prevent endless loading states
			metadataStore.update((state) => ({
				...state,
				isLoading: false,
				isLoaded: true,
				error: 'Cannot load metadata in server context'
			}));

			return {}; // Return empty data for SSR
		}

		// Try multiple possible locations for the metadata file
		const possiblePaths = [
			// New paths that ensure we're loading from the correct public location
			'data/sequence_metadata.json',
		];

		let loadedData: Record<string, MetadataItem> = {};
		let errorMessages: string[] = [];

		for (const path of possiblePaths) {
			try {
				console.log(`Attempting to load metadata from ${path}...`);
				const response = await safeFetch(path);

				if (response.ok) {
					const data = await response.json();
					console.log(`Successfully loaded metadata from ${path}`);

					// Debug: Log the structure of the first item
					const sampleKeys = Object.keys(data).slice(0, 1);
					if (sampleKeys.length > 0) {
						const sampleItem = data[sampleKeys[0]];
						console.log('Sample metadata item structure:', {
							key: sampleKeys[0],
							hasSequence: !!sampleItem.sequence,
							sequenceType: Array.isArray(sampleItem.sequence)
								? 'array'
								: typeof sampleItem.sequence,
							sequenceLength: Array.isArray(sampleItem.sequence)
								? sampleItem.sequence.length
								: 'N/A',
							firstElement:
								Array.isArray(sampleItem.sequence) && sampleItem.sequence.length > 0
									? typeof sampleItem.sequence[0]
									: 'N/A',
							hasTags: !!sampleItem.tags,
							isFavorite: !!sampleItem.is_favorite
						});
					}

					// Update store with loaded data
					metadataStore.update((state) => ({
						...state,
						data,
						isLoading: false,
						isLoaded: true,
						error: null
					}));

					console.log(`Loaded metadata for ${Object.keys(data).length} sequences`);
					loadedData = data;

					// Successfully loaded, so exit the loop
					return data;
				}
				console.warn(
					`Failed to load metadata from ${path}: ${response.status} ${response.statusText}`
				);
				errorMessages.push(
					`Failed to load from ${path}: ${response.status} ${response.statusText}`
				);
			} catch (error) {
				console.warn(`Error loading metadata from ${path}:`, error);
				errorMessages.push(
					`Error loading from ${path}: ${error instanceof Error ? error.message : String(error)}`
				);
			}
		}

		// If we get here, all attempts failed but we should still update the store
		// to prevent UI from hanging indefinitely
		metadataStore.update((state) => ({
			...state,
			isLoading: false,
			isLoaded: true, // Mark as loaded even though it failed
			error: errorMessages.join('; ')
		}));

		// Log the error but don't throw - return empty object instead
		console.error('Failed to load metadata from any location:', errorMessages);
		return {};
	})();

	try {
		return await loadingPromise;
	} catch (error) {
		// Ensure any promise rejection is caught and handled
		console.error('Unexpected error during metadata loading:', error);

		metadataStore.update((state) => ({
			...state,
			isLoading: false,
			isLoaded: true,
			error: error instanceof Error ? error.message : 'Unknown error loading metadata'
		}));

		return {};
	} finally {
		// Always reset the loading promise after completion or error
		setTimeout(() => {
			loadingPromise = null;
		}, 100);
	}
}

/**
 * Initialize the metadata extractor
 * Will load metadata if not already loaded
 */
export async function initializeMetadata(): Promise<void> {
	try {
		await Promise.race([
			loadMetadata(),
			new Promise((_, reject) => {
				setTimeout(() => reject(new Error('Metadata loading timed out')), 5000);
			})
		]);
	} catch (error) {
		console.error('Metadata initialization timed out or failed:', error);
		// Update the store to indicate failure but mark as loaded
		metadataStore.update((state) => ({
			...state,
			isLoading: false,
			isLoaded: true,
			error: error instanceof Error ? error.message : 'Metadata loading timed out'
		}));
	}
}

// Only trigger initial load in browser context
if (browser) {
	initializeMetadata().catch((error) => {
		console.error('Error during initial metadata load:', error);
	});
}

/**
 * Get all available sequences with their thumbnails
 * @returns Array of sequence objects with id, name, thumbnailUrl, and sequenceData
 */
export function getAllSequences(): SequenceWithThumbnail[] {
	// First try getting from the derived store
	let sequences: SequenceWithThumbnail[] = [];
	const unsubscribe = sequencesStore.subscribe((value) => {
		sequences = value;
	});
	unsubscribe();

	// If we got sequences from the derived store, use them
	if (sequences.length > 0) {
		console.log(`getAllSequences: Found ${sequences.length} sequences from the derived store`);
		return sequences;
	}

	// If no sequences from derived store, try direct conversion
	console.warn('Derived store returned no sequences, trying direct conversion');
	let rawData = {};
	let isLoaded = false;
	const unsubMetadata = metadataStore.subscribe((state) => {
		rawData = state.data;
		isLoaded = state.isLoaded;
	});
	unsubMetadata();

	// Only convert if the metadata is actually loaded
	if (isLoaded && Object.keys(rawData).length > 0) {
		const directSequences = convertRawMetadataToSequences(rawData);
		console.log(`getAllSequences: Found ${directSequences.length} sequences via direct conversion`);
		return directSequences;
	}

	console.warn('No sequences found in metadata (either not loaded yet or empty)');
	return [];
}

/**
 * Extract metadata from a thumbnail
 * @param thumbnailUrl - The URL of the thumbnail
 * @returns The extracted metadata or null if not found
 */
export function extractMetadataFromThumbnail(thumbnailUrl: string): SequenceData | null {
	// Get current store value
	let data: Record<string, MetadataItem> = {};

	// Subscribe to the store to get the current data
	metadataStore.subscribe((state) => {
		data = state.data;
	})();

	// Normalize the path
	const normalizedPath = thumbnailUrl.startsWith('/') ? thumbnailUrl : `/${thumbnailUrl}`;

	// Look up the metadata in our pre-extracted data
	const metadata = data[normalizedPath];

	if (metadata && metadata.sequence) {
		return metadata.sequence;
	}

	console.warn(`No metadata found for ${thumbnailUrl}`);
	return null;
}

/**
 * Get a sequence by its ID
 * @param id - The sequence ID
 * @returns The sequence object or null if not found
 */
export function getSequenceById(id: string): SequenceWithThumbnail | null {
	const sequences = getAllSequences();
	return sequences.find((seq) => seq.id.toLowerCase() === id.toLowerCase()) || null;
}

/**
 * Get all available tags from all sequences
 * @returns Array of unique tags
 */
export function getAllTags(): string[] {
	const tags = new Set<string>();

	// Get current store value
	let data: Record<string, MetadataItem> = {};
	metadataStore.subscribe((state) => {
		data = state.data;
	})();

	for (const metadata of Object.values(data)) {
		if (metadata.tags) {
			metadata.tags.forEach((tag) => tags.add(tag));
		}
	}

	return Array.from(tags).sort();
}

/**
 * Get sequences filtered by tag
 * @param tag - The tag to filter by
 * @returns Array of sequences with the specified tag
 */
export function getSequencesByTag(tag: string): SequenceWithThumbnail[] {
	const sequences = getAllSequences();
	return sequences.filter((seq) => seq.tags.includes(tag));
}

/**
 * Get favorite sequences
 * @returns Array of favorite sequences
 */
export function getFavoriteSequences(): SequenceWithThumbnail[] {
	const sequences = getAllSequences();
	return sequences.filter((seq) => seq.isFavorite);
}
